spring.application.name=TaskManager



# MongoDB Connection
spring.data.mongodb.database=taskManager
spring.data.mongodb.uri=mongodb://localhost:27017/TaskM

# JPA (for reference if used)
spring.data.mongodb.repositories.enabled=true

# Logging
logging.level.org.springframework=INFO
logging.level.com.MiraiEdge=DEBUG


#JWT CONFIG 
app.jwt.secret=your_jwt_secret_key_here
app.jwt.expiration=86400000  # 1 day in milliseconds

