spring.application.name=TaskManager
# === MongoDB Configuration ===
spring.data.mongodb.uri=mongodb://localhost:27017/taskdb

# === JWT Secret Key ===
jwt.secret=secret123

# === Server Configuration ===
server.port=8081